/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AMS;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author m_nou
 */
public class Applicant_details extends javax.swing.JFrame {

    /**
     * Creates new form Applicant_details
     */
    Person pr;
    AmbulanceManagemenrSystem ams;
    String off_id;
    public Applicant_details(Person pr,String id) {
        initComponents();
        jTextField1.setEditable(false);
        this.pr = pr;
        this.off_id = id;
        ams = AmbulanceManagemenrSystem.driver_instance();
        show_profile();
    }
    
    private void show_profile()
    {
        if(pr.getType().equals("Driver"))
        {
            Drivers dr = (Drivers) pr;
            jTextField1.setText(dr.getName());
            jTextField2.setText(dr.getFathername());
            jTextField3.setText(dr.getCnic());
            jTextField4.setText(dr.getDOB());
            jTextField5.setText(dr.getNumber());
            jTextField6.setText(dr.getGender());
            jTextField7.setText(dr.getEmail());
            jTextField8.setText(dr.getType());
            jTextField9.setText(dr.getRecruit_test_marks()+"");
            File f = new File("..\\Ambulance Managemenr System\\src\\Images\\"+dr.getDriving_licence());
            try {
                BufferedImage img = null;
            img = ImageIO.read(new File(f.getAbsolutePath()));
            Image img1= img.getScaledInstance(AttachFileLabel.getWidth(),AttachFileLabel.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon format = new ImageIcon(img1);
            AttachFileLabel.setIcon(format);
            } catch (Exception e) {
            }
        }
        else
        {
            EMT dr = (EMT) pr;
            jTextField1.setText(dr.getName());
            jTextField2.setText(dr.getFathername());
            jTextField3.setText(dr.getCnic());
            jTextField4.setText(dr.getDOB());
            jTextField5.setText(dr.getNumber());
            jTextField6.setText(dr.getGender());
            jTextField7.setText(dr.getEmail());
            jTextField8.setText(dr.getType());
            jTextField9.setText(dr.getRecruit_test_marks()+"");
            File f = new File("..\\Ambulance Managemenr System\\src\\Images\\"+dr.getCertificate());
            try {
                BufferedImage img = null;
            img = ImageIO.read(new File(f.getAbsolutePath()));
            Image img1= img.getScaledInstance(AttachFileLabel.getWidth(),AttachFileLabel.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon format = new ImageIcon(img1);
            AttachFileLabel.setIcon(format);
            } catch (Exception e) {
            }
        }    
        
    }

    private Applicant_details() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AttachFileLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        LoginButtom = new javax.swing.JLabel();
        LoginButtom1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(21, 32, 47));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ambulance Management System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 235, 40));

        jLabel3.setBackground(new java.awt.Color(29, 42, 53));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 40, 40));

        jLabel6.setBackground(new java.awt.Color(29, 42, 53));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 52)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Applicant Detail:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setText("Full Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jTextField1.setText("jTextField1");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 150, -1));

        jLabel5.setText("Father Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jTextField2.setText("jTextField1");
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 150, -1));

        jTextField3.setText("jTextField1");
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 150, -1));

        jLabel7.setText("CNIC:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel8.setText("Date of Birth:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jTextField4.setText("jTextField1");
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 150, -1));

        jLabel9.setText("Number:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jTextField5.setText("jTextField1");
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, -1));

        jLabel10.setText("Gender:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jTextField6.setText("jTextField1");
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 150, -1));

        jLabel11.setText("Email:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jTextField7.setText("jTextField1");
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 150, -1));

        jLabel12.setText("Type:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jTextField8.setText("jTextField1");
        jTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 150, -1));

        jTextField9.setText("jTextField1");
        jTextField9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 150, -1));

        jLabel13.setText("Obtain Marks:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        AttachFileLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(AttachFileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 350, 300));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Evening", "Night" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 130, -1));

        LoginButtom.setBackground(new java.awt.Color(29, 42, 53));
        LoginButtom.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LoginButtom.setForeground(new java.awt.Color(255, 255, 255));
        LoginButtom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginButtom.setText("Reject");
        LoginButtom.setOpaque(true);
        LoginButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtomMouseExited(evt);
            }
        });
        jPanel1.add(LoginButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 90, 50));

        LoginButtom1.setBackground(new java.awt.Color(29, 42, 53));
        LoginButtom1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LoginButtom1.setForeground(new java.awt.Color(255, 255, 255));
        LoginButtom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginButtom1.setText("Recruit");
        LoginButtom1.setOpaque(true);
        LoginButtom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtom1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtom1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtom1MouseExited(evt);
            }
        });
        jPanel1.add(LoginButtom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 90, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        this.setState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        jLabel6.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void LoginButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtomMouseClicked
        // TODO add your handling code here:
        if(pr.getType().equals("Driver"))
        {
            Drivers dr = (Drivers) pr;
        File f = new File("..\\Ambulance Managemenr System\\src\\Images\\"+dr.getDriving_licence());
        f.delete();
       this.setVisible(false);
        }
        else
        {
            EMT et = (EMT) pr;
        File f = new File("..\\Ambulance Managemenr System\\src\\Images\\"+et.getCertificate());
        f.delete();
        this.setVisible(false);
        }
        
    }//GEN-LAST:event_LoginButtomMouseClicked

    private void LoginButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtomMouseEntered
        // TODO add your handling code here:
        LoginButtom.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_LoginButtomMouseEntered

    private void LoginButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtomMouseExited
        // TODO add your handling code here:
        LoginButtom.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_LoginButtomMouseExited

    private void LoginButtom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtom1MouseClicked
        // TODO add your handling code here:
       if(this.pr.getType().equals("Driver"))
       {
           Drivers dr = (Drivers) pr;
           String a = jComboBox1.getSelectedItem().toString();
           Person per = new Drivers( a, dr.getName(), dr.getFathername(), dr.getCnic(), dr.getDOB(), dr.getGender(),dr.getEmail(), dr.getNumber(), dr.getDriving_licence(), 0);
           Drivers tr = (Drivers)per;
           tr.setOff_id(off_id);
           ams.getPerson_list().insert(per);
           this.setVisible(false);
       }
       else
       {
       EMT dr = (EMT) pr;
           String a = jComboBox1.getSelectedItem().toString();
           Person per = new EMT( a, dr.getName(), dr.getFathername(), dr.getCnic(), dr.getDOB(), dr.getGender(),dr.getEmail(), dr.getNumber(), dr.getCertificate(), 0);
           EMT tr = (EMT)per;
           tr.setOff_id(off_id);
           ams.getPerson_list().insert(per);
           this.setVisible(false);
       
       }

    }//GEN-LAST:event_LoginButtom1MouseClicked

    private void LoginButtom1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtom1MouseEntered
        // TODO add your handling code here:
        LoginButtom1.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_LoginButtom1MouseEntered

    private void LoginButtom1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtom1MouseExited
        // TODO add your handling code here:
        LoginButtom1.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_LoginButtom1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Applicant_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Applicant_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Applicant_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Applicant_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Applicant_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AttachFileLabel;
    private javax.swing.JLabel LoginButtom;
    private javax.swing.JLabel LoginButtom1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
