/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AMS;

/**
 *
 * @author m_nou
 */
public class CallOperatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form CallOperatorFrame
     */
    public CallOperatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BtnPanel = new javax.swing.JPanel();
        JobapplyBtn1 = new javax.swing.JLabel();
        JobapplyBtn2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JobapplyBtn6 = new javax.swing.JLabel();
        LoginButtom2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(970, 540));
        setMinimumSize(new java.awt.Dimension(970, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(21, 32, 47));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ambulance Management System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 235, 30));

        jLabel3.setBackground(new java.awt.Color(29, 42, 53));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 40, 40));

        jLabel6.setBackground(new java.awt.Color(29, 42, 53));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 52)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 30, 40));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-users-30.png"))); // NOI18N
        jLabel17.setText("Profile");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 0, 90, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 40));

        BtnPanel.setBackground(new java.awt.Color(29, 42, 53));
        BtnPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JobapplyBtn1.setBackground(new java.awt.Color(29, 42, 53));
        JobapplyBtn1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        JobapplyBtn1.setForeground(new java.awt.Color(255, 255, 255));
        JobapplyBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobapplyBtn1.setText("Reports");
        JobapplyBtn1.setOpaque(true);
        JobapplyBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobapplyBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JobapplyBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobapplyBtn1MouseExited(evt);
            }
        });
        BtnPanel.add(JobapplyBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 57));

        JobapplyBtn2.setBackground(new java.awt.Color(29, 42, 53));
        JobapplyBtn2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        JobapplyBtn2.setForeground(new java.awt.Color(255, 255, 255));
        JobapplyBtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobapplyBtn2.setText("Chat Box");
        JobapplyBtn2.setOpaque(true);
        JobapplyBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobapplyBtn2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JobapplyBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobapplyBtn2MouseExited(evt);
            }
        });
        BtnPanel.add(JobapplyBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 180, 57));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-ambulance-90.png"))); // NOI18N
        BtnPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 110));

        JobapplyBtn6.setBackground(new java.awt.Color(29, 42, 53));
        JobapplyBtn6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        JobapplyBtn6.setForeground(new java.awt.Color(255, 255, 255));
        JobapplyBtn6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobapplyBtn6.setText("Logout");
        JobapplyBtn6.setOpaque(true);
        JobapplyBtn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobapplyBtn6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JobapplyBtn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobapplyBtn6MouseExited(evt);
            }
        });
        BtnPanel.add(JobapplyBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 180, 57));

        LoginButtom2.setBackground(new java.awt.Color(29, 42, 53));
        LoginButtom2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LoginButtom2.setForeground(new java.awt.Color(255, 255, 255));
        LoginButtom2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginButtom2.setText("Assign Patients");
        LoginButtom2.setOpaque(true);
        LoginButtom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtom2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtom2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtom2MouseExited(evt);
            }
        });
        BtnPanel.add(LoginButtom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 57));

        getContentPane().add(BtnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 790, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        this.setState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        jLabel6.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
//        DisplayProfile();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void JobapplyBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_JobapplyBtn1MouseClicked

    private void JobapplyBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn1MouseEntered
        // TODO add your handling code here:

        JobapplyBtn1.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_JobapplyBtn1MouseEntered

    private void JobapplyBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn1MouseExited
        // TODO add your handling code here:

        JobapplyBtn1.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_JobapplyBtn1MouseExited

    private void JobapplyBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JobapplyBtn2MouseClicked

    private void JobapplyBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn2MouseEntered
        // TODO add your handling code here:

        JobapplyBtn2.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_JobapplyBtn2MouseEntered

    private void JobapplyBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn2MouseExited
        // TODO add your handling code here:
        JobapplyBtn2.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_JobapplyBtn2MouseExited

    private void JobapplyBtn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        LoginFrame fr = new LoginFrame();
        fr.setVisible(true);
    }//GEN-LAST:event_JobapplyBtn6MouseClicked

    private void JobapplyBtn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JobapplyBtn6MouseEntered

    private void JobapplyBtn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JobapplyBtn6MouseExited

    private void LoginButtom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtom2MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
//        jComboBox2.removeAllItems();
//        for (int i = 0; i < ams.getRes_off_list().size(); i++) {
//            if (ams.getRes_off_list().get(i).getManager_id().equals(" ")) {
//                String ss = ams.getRes_off_list().get(i).getName() + "," + ams.getRes_off_list().get(i).getRescue_off_id();
//                jComboBox2.addItem(ss);
//            }
//        }
    }//GEN-LAST:event_LoginButtom2MouseClicked

    private void LoginButtom2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtom2MouseEntered
        // TODO add your handling code here:
        LoginButtom2.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_LoginButtom2MouseEntered

    private void LoginButtom2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtom2MouseExited
        // TODO add your handling code here:
        LoginButtom2.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_LoginButtom2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CallOperatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CallOperatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CallOperatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CallOperatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CallOperatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JLabel JobapplyBtn1;
    private javax.swing.JLabel JobapplyBtn2;
    private javax.swing.JLabel JobapplyBtn6;
    private javax.swing.JLabel LoginButtom2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
