/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AMS;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Aadi
 */
public class EMTForm extends javax.swing.JFrame {

    /**
     * Creates new form EMTForm
     */
        EMT man_cur;
    AmbulanceManagemenrSystem ams;
    public EMTForm(EMT p) {
        initComponents();
        ChangePanel.setVisible(false);
        Update.setVisible(false);
        forPicName.setVisible(false);
        BtnPanel.setVisible(false);
        jPanel2.setVisible(false);
        this.man_cur = p;
    }

    public EMTForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfilePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        ProfilePic = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ManPass = new javax.swing.JTextField();
        BankName = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ContactNo = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        Qualifcation5 = new javax.swing.JTextField();
        ManId = new javax.swing.JTextField();
        CNIC = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Qualification = new javax.swing.JTextField();
        AccNo = new javax.swing.JTextField();
        AccountTitle = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        DelDP = new javax.swing.JLabel();
        ChangeDP = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        ChangePanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        forPicName = new javax.swing.JLabel();
        Update = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        BtnPanel = new javax.swing.JPanel();
        JobapplyBtn = new javax.swing.JLabel();
        LoginButtom = new javax.swing.JLabel();
        JobapplyBtn1 = new javax.swing.JLabel();
        JobapplyBtn2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JobapplyBtn3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        parkingpanel = new javax.swing.JPanel();
        LoginLabel3 = new javax.swing.JLabel();
        LoginLabel4 = new javax.swing.JLabel();
        LoginLabel5 = new javax.swing.JLabel();
        LoginLabel6 = new javax.swing.JLabel();
        amb_1 = new javax.swing.JLabel();
        amb_6 = new javax.swing.JLabel();
        amb_11 = new javax.swing.JLabel();
        amb_16 = new javax.swing.JLabel();
        amb_17 = new javax.swing.JLabel();
        amb_12 = new javax.swing.JLabel();
        amb_7 = new javax.swing.JLabel();
        amb_2 = new javax.swing.JLabel();
        amb_18 = new javax.swing.JLabel();
        amb_13 = new javax.swing.JLabel();
        amb_8 = new javax.swing.JLabel();
        amb_3 = new javax.swing.JLabel();
        amb_9 = new javax.swing.JLabel();
        amb_19 = new javax.swing.JLabel();
        amb_4 = new javax.swing.JLabel();
        amb_14 = new javax.swing.JLabel();
        amb_10 = new javax.swing.JLabel();
        amb_15 = new javax.swing.JLabel();
        amb_20 = new javax.swing.JLabel();
        amb_5 = new javax.swing.JLabel();
        bike_4 = new javax.swing.JLabel();
        bike_1 = new javax.swing.JLabel();
        bike_2 = new javax.swing.JLabel();
        bike_3 = new javax.swing.JLabel();
        bike_5 = new javax.swing.JLabel();
        fire_1 = new javax.swing.JLabel();
        fire_2 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProfilePanel.setBackground(new java.awt.Color(255, 255, 255));
        ProfilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 174, 174));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        ProfilePanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 220));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setAlignmentY(0.0F);
        jSeparator1.setPreferredSize(new java.awt.Dimension(40, 2));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 970, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-dashboard-32.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-edit-account-32.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-password-reset-32.png"))); // NOI18N
        jLabel17.setToolTipText("");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 50, 40));

        jLabel18.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("EMT Profile");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 180, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Garden Town, Gulberg, Lahore");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 170, -1));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-detail-32_1.png"))); // NOI18N
        jLabel24.setText("ATTEN. DETAILs");
        jLabel24.setToolTipText("");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 160, -1));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-attendance-32.png"))); // NOI18N
        jLabel31.setText("MARK ATTENDANCE");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 170, -1));

        Name.setEditable(false);
        Name.setBackground(new java.awt.Color(51, 51, 51));
        Name.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Zain Hassan");
        Name.setBorder(null);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel5.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 160, 20));

        ProfilePanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 140));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("SKILLS & MOTIVE");
        ProfilePanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 120, -1));

        ManPass.setEditable(false);
        ManPass.setBackground(new java.awt.Color(255, 255, 255));
        ManPass.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        ManPass.setText("man_9$DA");
        ManPass.setBorder(null);
        ManPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManPassActionPerformed(evt);
            }
        });
        ProfilePanel.add(ManPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 160, 20));

        BankName.setEditable(false);
        BankName.setBackground(new java.awt.Color(255, 255, 255));
        BankName.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        BankName.setText("Bank Name");
        BankName.setBorder(null);
        BankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankNameActionPerformed(evt);
            }
        });
        ProfilePanel.add(BankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 160, 20));

        Email.setEditable(false);
        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Email.setText("isharjeel63@gmail.com");
        Email.setBorder(null);
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        ProfilePanel.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 160, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Contact Information");
        ProfilePanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 120, -1));

        ContactNo.setEditable(false);
        ContactNo.setBackground(new java.awt.Color(255, 255, 255));
        ContactNo.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        ContactNo.setText("03451698213");
        ContactNo.setBorder(null);
        ContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNoActionPerformed(evt);
            }
        });
        ProfilePanel.add(ContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 160, 20));

        DOB.setEditable(false);
        DOB.setBackground(new java.awt.Color(255, 255, 255));
        DOB.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        DOB.setText("11-7-2000");
        DOB.setBorder(null);
        DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBActionPerformed(evt);
            }
        });
        ProfilePanel.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 160, 20));

        Qualifcation5.setEditable(false);
        Qualifcation5.setBackground(new java.awt.Color(255, 255, 255));
        Qualifcation5.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Qualifcation5.setText("MALE");
        Qualifcation5.setBorder(null);
        Qualifcation5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qualifcation5ActionPerformed(evt);
            }
        });
        ProfilePanel.add(Qualifcation5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 160, 20));

        ManId.setEditable(false);
        ManId.setBackground(new java.awt.Color(255, 255, 255));
        ManId.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        ManId.setText("man-2@manager.com");
        ManId.setBorder(null);
        ManId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManIdActionPerformed(evt);
            }
        });
        ProfilePanel.add(ManId, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 160, 20));

        CNIC.setEditable(false);
        CNIC.setBackground(new java.awt.Color(255, 255, 255));
        CNIC.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        CNIC.setText("3410109561127");
        CNIC.setBorder(null);
        CNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNICActionPerformed(evt);
            }
        });
        ProfilePanel.add(CNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 160, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Basic Information");
        ProfilePanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 120, -1));

        Qualification.setEditable(false);
        Qualification.setBackground(new java.awt.Color(255, 255, 255));
        Qualification.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Qualification.setText("MSC Business");
        Qualification.setBorder(null);
        Qualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QualificationActionPerformed(evt);
            }
        });
        ProfilePanel.add(Qualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 160, 20));

        AccNo.setEditable(false);
        AccNo.setBackground(new java.awt.Color(255, 255, 255));
        AccNo.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        AccNo.setText("Account Number");
        AccNo.setBorder(null);
        AccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccNoActionPerformed(evt);
            }
        });
        ProfilePanel.add(AccNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 160, 20));

        AccountTitle.setEditable(false);
        AccountTitle.setBackground(new java.awt.Color(255, 255, 255));
        AccountTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        AccountTitle.setText("Account Title");
        AccountTitle.setBorder(null);
        AccountTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountTitleActionPerformed(evt);
            }
        });
        ProfilePanel.add(AccountTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 160, 20));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        DelDP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DelDP.setForeground(new java.awt.Color(255, 255, 255));
        DelDP.setText("Delete");
        DelDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelDPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(DelDP)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DelDP, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        ProfilePanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        ChangeDP.setBackground(new java.awt.Color(51, 51, 51));
        ChangeDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangeDPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangeDPMouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Change");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel27MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout ChangeDPLayout = new javax.swing.GroupLayout(ChangeDP);
        ChangeDP.setLayout(ChangeDPLayout);
        ChangeDPLayout.setHorizontalGroup(
            ChangeDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangeDPLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel27)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        ChangeDPLayout.setVerticalGroup(
            ChangeDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        ProfilePanel.add(ChangeDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("-  Helping others is a scret");
        ProfilePanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 170, -1));

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("   Sauce of LIFE...");
        ProfilePanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 170, 20));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("MS in Socail services");
        ProfilePanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 129, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Account Details");
        ProfilePanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 120, -1));

        ChangePanel.setBackground(new java.awt.Color(255, 255, 255));
        ChangePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CHANGE PASSWORD");

        jLabel32.setBackground(new java.awt.Color(51, 51, 51));
        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("X");
        jLabel32.setOpaque(true);
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32MouseExited(evt);
            }
        });

        jLabel33.setBackground(new java.awt.Color(51, 51, 51));
        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 52)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("-");
        jLabel33.setOpaque(true);
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel33MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel33MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        ChangePanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField1.setText("OLD Password");
        ChangePanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 72, 305, 45));

        jTextField2.setText("New Password");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        ChangePanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 128, 305, 40));

        jTextField3.setText("Enter OTP (send Via your Emai).l");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        ChangePanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 186, 305, 43));

        jPanel11.setBackground(new java.awt.Color(255, 174, 174));

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Change Password");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ChangePanel.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 240, 305, -1));

        ProfilePanel.add(ChangePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 530, 360));

        forPicName.setText("jLabel26");
        ProfilePanel.add(forPicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        Update.setBackground(new java.awt.Color(255, 174, 174));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Update");

        javax.swing.GroupLayout UpdateLayout = new javax.swing.GroupLayout(Update);
        Update.setLayout(UpdateLayout);
        UpdateLayout.setHorizontalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        UpdateLayout.setVerticalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ProfilePanel.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 150, 40));

        getContentPane().add(ProfilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        jPanel2.setBackground(new java.awt.Color(21, 32, 47));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ambulance Management System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 235, 30));

        jLabel3.setBackground(new java.awt.Color(29, 42, 53));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 40, 40));

        jLabel6.setBackground(new java.awt.Color(29, 42, 53));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 52)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 30, 40));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-users-30.png"))); // NOI18N
        jLabel26.setText("Profile");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 0, 90, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 40));

        BtnPanel.setBackground(new java.awt.Color(29, 42, 53));
        BtnPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JobapplyBtn.setBackground(new java.awt.Color(29, 42, 53));
        JobapplyBtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        JobapplyBtn.setForeground(new java.awt.Color(255, 255, 255));
        JobapplyBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobapplyBtn.setText("Log Out");
        JobapplyBtn.setOpaque(true);
        JobapplyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobapplyBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JobapplyBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobapplyBtnMouseExited(evt);
            }
        });
        BtnPanel.add(JobapplyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 180, 57));

        LoginButtom.setBackground(new java.awt.Color(29, 42, 53));
        LoginButtom.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LoginButtom.setForeground(new java.awt.Color(255, 255, 255));
        LoginButtom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginButtom.setText("Assign Patient");
        LoginButtom.setOpaque(true);
        LoginButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtomMouseExited(evt);
            }
        });
        BtnPanel.add(LoginButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 57));

        JobapplyBtn1.setBackground(new java.awt.Color(29, 42, 53));
        JobapplyBtn1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        JobapplyBtn1.setForeground(new java.awt.Color(255, 255, 255));
        JobapplyBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobapplyBtn1.setText("Attendance");
        JobapplyBtn1.setOpaque(true);
        JobapplyBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobapplyBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JobapplyBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobapplyBtn1MouseExited(evt);
            }
        });
        BtnPanel.add(JobapplyBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 57));

        JobapplyBtn2.setBackground(new java.awt.Color(29, 42, 53));
        JobapplyBtn2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        JobapplyBtn2.setForeground(new java.awt.Color(255, 255, 255));
        JobapplyBtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobapplyBtn2.setText("Parking");
        JobapplyBtn2.setOpaque(true);
        JobapplyBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobapplyBtn2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JobapplyBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobapplyBtn2MouseExited(evt);
            }
        });
        BtnPanel.add(JobapplyBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 180, 57));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-ambulance-90.png"))); // NOI18N
        BtnPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, 110));

        JobapplyBtn3.setBackground(new java.awt.Color(29, 42, 53));
        JobapplyBtn3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        JobapplyBtn3.setForeground(new java.awt.Color(255, 255, 255));
        JobapplyBtn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobapplyBtn3.setText("Dow.Salry Slip");
        JobapplyBtn3.setOpaque(true);
        JobapplyBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobapplyBtn3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JobapplyBtn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobapplyBtn3MouseExited(evt);
            }
        });
        BtnPanel.add(JobapplyBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 180, 57));

        getContentPane().add(BtnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 0, 781, 487));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 487));

        jTabbedPane1.addTab("tab2", jPanel1);

        parkingpanel.setBackground(new java.awt.Color(255, 255, 255));
        parkingpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginLabel3.setText("Fire Brigade Parking:");
        LoginLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(LoginLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        LoginLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LoginLabel4.setText("Parking:");
        LoginLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(LoginLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        LoginLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginLabel5.setText("Ambulance Parking:");
        LoginLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(LoginLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        LoginLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginLabel6.setText("Bike Parking:");
        LoginLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(LoginLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, -1));

        amb_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 50, 60));

        amb_6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 50, 60));

        amb_11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 50, 60));

        amb_16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 50, 60));

        amb_17.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 50, 60));

        amb_12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 50, 60));

        amb_7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, 60));

        amb_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 50, 60));

        amb_18.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 50, 60));

        amb_13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 50, 60));

        amb_8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 50, 60));

        amb_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 50, 60));

        amb_9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 50, 60));

        amb_19.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 50, 60));

        amb_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 50, 60));

        amb_14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 50, 60));

        amb_10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 50, 60));

        amb_15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 50, 60));

        amb_20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 50, 60));

        amb_5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(amb_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 50, 60));

        bike_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(bike_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 30, 50));

        bike_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(bike_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 30, 50));

        bike_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(bike_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 30, 50));

        bike_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(bike_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 30, 50));

        bike_5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(bike_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 30, 50));

        fire_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(fire_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 50, 80));

        fire_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(fire_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 50, 80));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setText("Parking Slot is not allotted!");
        parkingpanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, -1, 20));

        jLabel36.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 30, 30));

        jLabel37.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 30, 30));

        jLabel38.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        parkingpanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 30, 30));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel39.setText("Vehicle is parked!");
        parkingpanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, 20));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel40.setText("Vehicle is dispatched!");
        parkingpanel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, -1, 20));

        jTabbedPane1.addTab("tab1", parkingpanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 970, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:\
        jPanel2.setVisible(true);
        ProfilePanel.setVisible(false);
        BtnPanel.setVisible(true);
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        Update.setVisible(true);
        DOB.setEditable(true);
        CNIC.setEditable(true);
        Qualification.setEditable(true);
        AccNo.setEditable(true);
        AccountTitle.setEditable(true);
        BankName.setEditable(true);
        ContactNo.setEditable(true);
        Email.setEditable(true);
        Border border = BorderFactory.createLineBorder(Color.GRAY, 1);
        Name.setBorder(border);
        DOB.setBorder(border);
        CNIC.setBorder(border);
        Qualification.setBorder(border);
        AccNo.setBorder(border);
        AccountTitle.setBorder(border);
        BankName.setBorder(border);
        ContactNo.setBorder(border);
        Email.setBorder(border);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        jLabel15.setBackground(new java.awt.Color(120,120,120));
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
        jLabel15.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        try {
            // TODO add your handling code here:
            Acount_detaiils.SendMail("isharjee63@gmail.com");
        } catch (Exception ex) {
            Logger.getLogger(ManagerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void ManPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManPassActionPerformed

    private void BankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankNameActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void ContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNoActionPerformed

    private void DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBActionPerformed

    private void Qualifcation5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qualifcation5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Qualifcation5ActionPerformed

    private void ManIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManIdActionPerformed

    private void CNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNICActionPerformed

    private void QualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QualificationActionPerformed

    private void AccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccNoActionPerformed

    private void AccountTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountTitleActionPerformed

    private void DelDPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelDPMouseClicked
        // TODO add your handling code here:
        ProfilePic.setIcon(null);
        String io = forPicName.getText();
        //BufferedImage imgg = ImageIO.read(new File("..\\Ambulance Managemenr System\\src\\Images\\"+io));
            File f = new File("..\\Ambulance Managemenr System\\src\\Images\\StaffPhoto"+io);
            f.delete();
    }//GEN-LAST:event_DelDPMouseClicked

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        // TODO add your handling code here:
        jPanel9.setBackground(new java.awt.Color(120,120,120));
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        // TODO add your handling code here:
        jPanel9.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_jPanel9MouseExited

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("files", ImageIO.getReaderFileSuffixes());
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        try {
            BufferedImage img = null;
            img = ImageIO.read(new File(f.getAbsolutePath()));
            Image img1 = img.getScaledInstance(ProfilePic.getWidth(), ProfilePic.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon format = new ImageIcon(img1);
            ProfilePic.setIcon(format);
            String filePath = f.getAbsolutePath();
            //System.out.println(filePath);
            String fie = filePath.replace("\\", "/");
                //System.out.println(fie);
                String[] filename = fie.split("/");
                int size = filename.length;
                String Fname = filename[size - 1];
                forPicName.setText(Fname);
                ImageIO.write(img, "jpeg", new File("..\\Ambulance Managemenr System\\src\\Images\\StaffPhoto"+Fname));
                forPicName.setText(Fname);
    }//GEN-LAST:event_jLabel27MouseClicked
    catch(Exception ex)
    {
        
    }
    }
    private void jLabel27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseEntered

    private void ChangeDPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeDPMouseEntered
        // TODO add your handling code here:
        ChangeDP.setBackground(new java.awt.Color(120,120,120));
    }//GEN-LAST:event_ChangeDPMouseEntered

    private void ChangeDPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeDPMouseExited
        // TODO add your handling code here:
        ChangeDP.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_ChangeDPMouseExited

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseEntered
        // TODO add your handling code here:
        jLabel32.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_jLabel32MouseEntered

    private void jLabel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseExited
        // TODO add your handling code here:
        jLabel32.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_jLabel32MouseExited

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:

        this.setState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseEntered
        // TODO add your handling code here:
        jLabel33.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_jLabel33MouseEntered

    private void jLabel33MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseExited
        // TODO add your handling code here:
        jLabel33.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_jLabel33MouseExited

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        // TODO add your handling code here:
        String name=Name.getText();
        String dob=DOB.getText();
        String cnic=CNIC.getText();
        String qual = Qualification.getText();
        String accNO=AccNo.getText();
        String Acctitle=AccountTitle.getText();
        String Bname=BankName.getText();
        String contNo=ContactNo.getText();
        String email = Email.getText();
        String MANID = ManId.getText();
        for(int i=0;i<ams.getPerson_list().size();i++)
        {
            if(ams.getPerson_list().get(i).getId_number().equals(MANID))
            {
                ams.getPerson_list().get(i).setName(name);
                ams.getPerson_list().get(i).setDOB(dob);
                ams.getPerson_list().get(i).setEmail(email);
                ams.getPerson_list().get(i).setCnic(cnic);
                Manager mana = (Manager) ams.getPerson_list().get(i);
                mana.setNumber(contNo);
                mana.setQalification(qual);
                mana.getAcc().setAcc_name(Acctitle);
                mana.getAcc().setAcc_num(accNO);
                mana.getAcc().setBank_name(Bname);
                JOptionPane.showMessageDialog(null,"Manager Details has been updated");
            }
        }
        Update.setVisible(false);
    }//GEN-LAST:event_UpdateMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        this.setState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        jLabel6.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        ProfilePanel.setVisible(true);
        jPanel2.setVisible(false);
        BtnPanel.setVisible(false);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void JobapplyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtnMouseClicked
        // TODO add your handling code here:
        LoginFrame job = new LoginFrame();
        job.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JobapplyBtnMouseClicked

    private void JobapplyBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtnMouseEntered
        // TODO add your handling code here:
        JobapplyBtn.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_JobapplyBtnMouseEntered

    private void JobapplyBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtnMouseExited
        // TODO add your handling code here:
        JobapplyBtn.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_JobapplyBtnMouseExited

    private void LoginButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtomMouseClicked
        // TODO add your handling code here:
        Assign_PatientForm APF = new Assign_PatientForm();
        APF.Controlpp.setText("2");
        System.out.println("In EMt "+APF.Controlpp.getText());
        APF.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_LoginButtomMouseClicked

    private void LoginButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtomMouseEntered
        // TODO add your handling code here:
        LoginButtom.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_LoginButtomMouseEntered

    private void LoginButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtomMouseExited
        // TODO add your handling code here:

        LoginButtom.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_LoginButtomMouseExited

    private void JobapplyBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_JobapplyBtn1MouseClicked

    private void JobapplyBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn1MouseEntered
        // TODO add your handling code here:

        JobapplyBtn1.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_JobapplyBtn1MouseEntered

    private void JobapplyBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn1MouseExited
        // TODO add your handling code here:

        JobapplyBtn1.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_JobapplyBtn1MouseExited

    private void JobapplyBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_JobapplyBtn2MouseClicked

    private void JobapplyBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn2MouseEntered
        // TODO add your handling code here:

        JobapplyBtn2.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_JobapplyBtn2MouseEntered

    private void JobapplyBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn2MouseExited
        // TODO add your handling code here:
        JobapplyBtn2.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_JobapplyBtn2MouseExited

    private void JobapplyBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JobapplyBtn3MouseClicked

    private void JobapplyBtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JobapplyBtn3MouseEntered

    private void JobapplyBtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JobapplyBtn3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMTForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNo;
    private javax.swing.JTextField AccountTitle;
    private javax.swing.JTextField BankName;
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JTextField CNIC;
    private javax.swing.JPanel ChangeDP;
    private javax.swing.JPanel ChangePanel;
    private javax.swing.JTextField ContactNo;
    private javax.swing.JTextField DOB;
    private javax.swing.JLabel DelDP;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel JobapplyBtn;
    private javax.swing.JLabel JobapplyBtn1;
    private javax.swing.JLabel JobapplyBtn2;
    private javax.swing.JLabel JobapplyBtn3;
    private javax.swing.JLabel LoginButtom;
    private javax.swing.JLabel LoginLabel3;
    private javax.swing.JLabel LoginLabel4;
    private javax.swing.JLabel LoginLabel5;
    private javax.swing.JLabel LoginLabel6;
    private javax.swing.JTextField ManId;
    private javax.swing.JTextField ManPass;
    private javax.swing.JTextField Name;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JLabel ProfilePic;
    private javax.swing.JTextField Qualifcation5;
    private javax.swing.JTextField Qualification;
    private javax.swing.JPanel Update;
    private javax.swing.JLabel amb_1;
    private javax.swing.JLabel amb_10;
    private javax.swing.JLabel amb_11;
    private javax.swing.JLabel amb_12;
    private javax.swing.JLabel amb_13;
    private javax.swing.JLabel amb_14;
    private javax.swing.JLabel amb_15;
    private javax.swing.JLabel amb_16;
    private javax.swing.JLabel amb_17;
    private javax.swing.JLabel amb_18;
    private javax.swing.JLabel amb_19;
    private javax.swing.JLabel amb_2;
    private javax.swing.JLabel amb_20;
    private javax.swing.JLabel amb_3;
    private javax.swing.JLabel amb_4;
    private javax.swing.JLabel amb_5;
    private javax.swing.JLabel amb_6;
    private javax.swing.JLabel amb_7;
    private javax.swing.JLabel amb_8;
    private javax.swing.JLabel amb_9;
    private javax.swing.JLabel bike_1;
    private javax.swing.JLabel bike_2;
    private javax.swing.JLabel bike_3;
    private javax.swing.JLabel bike_4;
    private javax.swing.JLabel bike_5;
    private javax.swing.JLabel fire_1;
    private javax.swing.JLabel fire_2;
    private javax.swing.JLabel forPicName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel parkingpanel;
    // End of variables declaration//GEN-END:variables
}
