/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AMS;

import DataStructures.LinkedList;
import DataStructures.RBTree;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author m_nou
 */
public class LoginFrame extends javax.swing.JFrame {

    AmbulanceManagemenrSystem ams;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();

        ams = AmbulanceManagemenrSystem.driver_instance();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnPanel = new javax.swing.JPanel();
        JobapplyBtn = new javax.swing.JLabel();
        LoginButtom = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JobPpanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        user_txxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pass_txt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        sep_hover = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(21, 32, 47));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ambulance Management System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 235, 30));

        jLabel3.setBackground(new java.awt.Color(29, 42, 53));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 40, 30));

        jLabel6.setBackground(new java.awt.Color(29, 42, 53));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 30));

        BtnPanel.setBackground(new java.awt.Color(29, 42, 53));
        BtnPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JobapplyBtn.setBackground(new java.awt.Color(29, 42, 53));
        JobapplyBtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        JobapplyBtn.setForeground(new java.awt.Color(255, 255, 255));
        JobapplyBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobapplyBtn.setText("Apply for job");
        JobapplyBtn.setOpaque(true);
        JobapplyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobapplyBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JobapplyBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobapplyBtnMouseExited(evt);
            }
        });
        BtnPanel.add(JobapplyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 57));

        LoginButtom.setBackground(new java.awt.Color(29, 42, 53));
        LoginButtom.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LoginButtom.setForeground(new java.awt.Color(255, 255, 255));
        LoginButtom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginButtom.setText("Login");
        LoginButtom.setOpaque(true);
        LoginButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtomMouseExited(evt);
            }
        });
        BtnPanel.add(LoginButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 57));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-ambulance-90.png"))); // NOI18N
        BtnPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 130));

        jPanel1.add(BtnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 380));

        JobPpanel.setBackground(new java.awt.Color(255, 255, 255));
        JobPpanel.setForeground(new java.awt.Color(255, 255, 255));
        JobPpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LoginLabel.setText("Login");
        JobPpanel.add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 38, 80, -1));

        jSeparator8.setBackground(new java.awt.Color(29, 42, 53));
        jSeparator8.setForeground(new java.awt.Color(29, 42, 53));
        JobPpanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 73, 71, 12));

        user_txxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        user_txxt.setForeground(new java.awt.Color(102, 102, 102));
        user_txxt.setText("Enter Provied E-mail");
        user_txxt.setBorder(null);
        user_txxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_txxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                user_txxtFocusLost(evt);
            }
        });
        user_txxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_txxtActionPerformed(evt);
            }
        });
        JobPpanel.add(user_txxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 101, 275, 35));

        jSeparator1.setBackground(new java.awt.Color(29, 42, 53));
        jSeparator1.setForeground(new java.awt.Color(29, 42, 53));
        JobPpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 142, 275, 10));

        pass_txt.setForeground(new java.awt.Color(102, 102, 102));
        pass_txt.setText("jPasswordField1");
        pass_txt.setBorder(null);
        pass_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_txtFocusLost(evt);
            }
        });
        JobPpanel.add(pass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 170, 275, 30));

        jSeparator2.setBackground(new java.awt.Color(29, 42, 53));
        jSeparator2.setForeground(new java.awt.Color(29, 42, 53));
        JobPpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 206, 275, 10));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Forgot Password");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JobPpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 255, 116, -1));

        sep_hover.setBackground(new java.awt.Color(29, 42, 53));
        sep_hover.setForeground(new java.awt.Color(29, 42, 53));
        JobPpanel.add(sep_hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 278, 105, 10));

        jPanel3.setBackground(new java.awt.Color(29, 42, 53));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign in");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JobPpanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 90, 40));

        jTabbedPane1.addTab("tab2", JobPpanel);

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", LoginPanel);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 510, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtomMouseEntered
        // TODO add your handling code here:
        LoginButtom.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_LoginButtomMouseEntered

    private void LoginButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtomMouseExited
        // TODO add your handling code here:

        LoginButtom.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_LoginButtomMouseExited

    private void JobapplyBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtnMouseEntered
        // TODO add your handling code here:
        JobapplyBtn.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_JobapplyBtnMouseEntered

    private void JobapplyBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtnMouseExited
        // TODO add your handling code here:
        JobapplyBtn.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_JobapplyBtnMouseExited

    private void user_txxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_txxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_txxtActionPerformed

    private void user_txxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_txxtFocusGained
        // TODO add your handling code here:
        if (user_txxt.getText().equals("Enter Provied E-mail")) {
            user_txxt.setText("");
        }
    }//GEN-LAST:event_user_txxtFocusGained

    private void user_txxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_txxtFocusLost
        // TODO add your handling code here:
        if (user_txxt.getText().equals("")) {
            user_txxt.setText("Enter Provied E-mail");
        }
    }//GEN-LAST:event_user_txxtFocusLost

    private void pass_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_txtFocusGained
        // TODO add your handling code here:
        if (pass_txt.getText().equals("jPasswordField1")) {
            pass_txt.setText("");
        }
    }//GEN-LAST:event_pass_txtFocusGained

    private void pass_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_txtFocusLost
        // TODO add your handling code here:
        if (pass_txt.getText().equals("")) {
            pass_txt.setText("jPasswordField1");
        }
    }//GEN-LAST:event_pass_txtFocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Admin.writeadmin();
        try {
            ams.save_person();
            ams.save_apply();
        } catch (IOException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        this.setState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setBackground(new java.awt.Color(102, 102, 102));

    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        jLabel6.setBackground(new java.awt.Color(29, 42, 53));
    }//GEN-LAST:event_jLabel6MouseExited

    private void JobapplyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobapplyBtnMouseClicked
        // TODO add your handling code here:
        JobFrame job = new JobFrame();
        job.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JobapplyBtnMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

        String email = user_txxt.getText();
        String password = pass_txt.getText();

        if (email.equals("Enter Provied E-mail") || password.equals("jPasswordField1")) {
            jSeparator2.setBackground(Color.red);
            jSeparator2.setForeground(Color.red);

            jSeparator1.setBackground(Color.red);
            jSeparator1.setForeground(Color.red);

        } else {
            String PersonType = AmbulanceManagemenrSystem.getPersonType(email).toLowerCase();
            if (!PersonType.equals("null")) {
                if (PersonType.equals("admin")) {
                    Admin ad = Admin.admin_instance();
                    if (ad.getId_number().equals(email)) {
                        jSeparator1.setBackground(new java.awt.Color(29, 42, 53));
                        jSeparator1.setForeground(new java.awt.Color(29, 42, 53));
                        if (ad.getPassword().equals(password)) {
                            AdminFrame obj = new AdminFrame();
                            obj.setVisible(true);
                            this.setVisible(false);
                        } else {
                            jSeparator2.setBackground(Color.red);
                            jSeparator2.setForeground(Color.red);
                        }
                    } else {
                        jSeparator1.setBackground(Color.red);
                        jSeparator1.setForeground(Color.red);
                    }
                } else if (PersonType.equals("manager")) {
                    // This Line will return all the Person of Manager Type from RBTree.
                    for (int i = 0; i < ams.getPerson_list().size(); i++) {
                        if (ams.getPerson_list().get(i).getType().equals("Manager")) {
                            Manager b = (Manager) ams.getPerson_list().get(i);
                            if (b.getId_number().equals(email)) {
                                if (b.getPassword().equals(password)) {
                                    try {
                                        ManagerFrame fg = new ManagerFrame(b);
                                        fg.setVisible(true);
                                        this.setVisible(false);
                                    } catch (IOException ex) {
                                        Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                } else {
                                    jSeparator2.setBackground(Color.red);
                                    jSeparator2.setForeground(Color.red);
                                }
                            } else {
                                jSeparator1.setBackground(Color.red);
                                jSeparator1.setForeground(Color.red);
                            }
                        }

                    }
                } else if (PersonType.equals("driver")) {
                    // This Line will return all the Person of Manager Type from RBTree.
                    for (int i = 0; i < ams.getPerson_list().size(); i++) {
                        if (ams.getPerson_list().get(i).getType().equals("Driver")) {
                            Drivers b = (Drivers) ams.getPerson_list().get(i);
                            if (b.getId_number().equals(email)) {
                                if (b.getPassword().equals(password)) {
                                   // ManagerFrame fg = new ManagerFrame(b);
                                   // fg.setVisible(true);
                                } else {
                                    jSeparator2.setBackground(Color.red);
                                    jSeparator2.setForeground(Color.red);
                                }
                            } else {
                                jSeparator1.setBackground(Color.red);
                                jSeparator1.setForeground(Color.red);
                            }
                        }

                    }
                } else if (PersonType.equals("emt")) {
                    // This Line will return all the Person of Manager Type from RBTree.
                    for (int i = 0; i < ams.getPerson_list().size(); i++) {
                        if (ams.getPerson_list().get(i).getType().equals("EMT")) {
                            EMT b = (EMT) ams.getPerson_list().get(i);
                            if (b.getId_number().equals(email)) {
                                if (b.getPassword().equals(password)) {
                                    EMTForm fg = new EMTForm(b);
                                    fg.setVisible(true);
                                } else {
                                    jSeparator2.setBackground(Color.red);
                                    jSeparator2.setForeground(Color.red);
                                }
                            } else {
                                jSeparator1.setBackground(Color.red);
                                jSeparator1.setForeground(Color.red);
                            }
                        }

                    }
                }
//                else if (PersonType.equals("manager")) {
//                    // This Line will return all the Person of Manager Type from RBTree.
//                    System.out.println("Hi");
//                    LinkedList<Person> list = RBTree.GetNodeOfSameType("Manager", ams.getProfiles_tree().getRoot());
//                    System.out.println("list size");
//                    System.out.println(list.size());
//                    for (int i = 0; i < list.size(); i++) {
//                        Manager b = (Manager) list.get(i);
//                        if (b.getId_number().equals(email)) {
//                            if (b.getPassword().equals(password)) {
//                         ManagerFrame fg = new ManagerFrame(b);
//                         fg.setVisible(true);
//                            } else {
//                                jSeparator2.setBackground(Color.red);
//                                jSeparator2.setForeground(Color.red);
//                            }
//                        } else {
//                            jSeparator1.setBackground(Color.red);
//                            jSeparator1.setForeground(Color.red);
//                        }
//
//                    }
//                } else if (PersonType.equals("driver")) {
//                    // This Line will return all the Person of Manager Type from RBTree.
//                    LinkedList<Person> list = RBTree.GetNodeOfSameType("Driver", ams.getProfiles_tree().getRoot());
//                    for (int i = 0; i < list.size(); i++) {
//                        Drivers b = (Drivers) list.DeleteFromStart();
//                        if (b.getId_number().equals(email)) {
//                            if (b.getPassword().equals(password)) {
//
//                            } else {
//                                jSeparator2.setBackground(Color.red);
//                                jSeparator2.setForeground(Color.red);
//                            }
//                        } else {
//                            jSeparator1.setBackground(Color.red);
//                            jSeparator1.setForeground(Color.red);
//                        }
//
//                    }
//                } else if (PersonType.equals("emt")) {
//                    // This Line will return all the Person of Manager Type from RBTree.
//                    LinkedList<Person> list = RBTree.GetNodeOfSameType("EMT", ams.getProfiles_tree().getRoot());
//                    for (int i = 0; i < list.size(); i++) {
//                        EMT b = (EMT) list.DeleteFromStart();
//                        if (b.getId_number().equals(email)) {
//                            if (b.getPassword().equals(password)) {
//
//                            } else {
//                                jSeparator2.setBackground(Color.red);
//                                jSeparator2.setForeground(Color.red);
//                            }
//                        } else {
//                            jSeparator1.setBackground(Color.red);
//                            jSeparator1.setForeground(Color.red);
//                        }
//
//                    }
//                }
//        else if (PersonType.equals("Call Operator")) {
//            // This Line will return all the Person of Manager Type from RBTree.
//            LinkedList<Person> list = RBTree.GetNodeOfSameType("Manager", ams.profiles_tree.getRoot());
//            for (int i = 0; i < list.size(); i++) {
//                Manager b = (Manager) list.DeleteFromStart();
//                if (b.getId_number().equals(email)) {
//                    if (b.getPassword().equals(password)) {
//
//                        
//                    } else {
//                        jSeparator2.setBackground(Color.red);
//                        jSeparator2.setForeground(Color.red);
//                    }
//                } else {
//                    jSeparator1.setBackground(Color.red);
//                    jSeparator1.setForeground(Color.red);
//                }
//
//            }
//        }

            } else {

                jSeparator1.setBackground(Color.red);
                jSeparator1.setForeground(Color.red);
            }

        }

    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JPanel JobPpanel;
    private javax.swing.JLabel JobapplyBtn;
    private javax.swing.JLabel LoginButtom;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField pass_txt;
    private javax.swing.JSeparator sep_hover;
    private javax.swing.JTextField user_txxt;
    // End of variables declaration//GEN-END:variables
}
